name: Release

on:
  push:
    branches:
      - 'release/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=${BRANCH_NAME#release/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.extract_version.outputs.branch_name }}
          destination_branch: "main"
          pr_title: "🚀 Release ${{ steps.extract_version.outputs.version }}"
          pr_body: |
            ## Release ${{ steps.extract_version.outputs.version }}

            This PR contains the release changes for version `${{ steps.extract_version.outputs.version }}`.

            ### Changes
            - Updated version files
            - Updated CHANGELOG.md
            - Ready for release

            ### After merge
            - [ ] Tag will be created automatically
            - [ ] GitHub release will be published

            ---

            **This PR was created automatically by the release workflow** 🤖
          pr_reviewer: "vs-borodin"
          pr_assignee: "vs-borodin"
          pr_label: "release,automated"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
